@startuml DTLS_Handshake_Configuration
skinparam backgroundColor LightGrey
skinparam activity {
  StartColor YellowGreen
  EndColor Tomato
  BackgroundColor White
  ArrowColor Black
}
start

:Initialize modem and connect to LTE network;
if (LTE connection established?) then (yes)
  :Create UDP socket;
  :Initialize WolfSSL;


  if (Use PSK or Certificates?) then (PSK)
    :Set up PSK identity and key;
    :Enable PSK;
  else (Certificates)
    :Load root CA;
    :Load client certificate and key;
  endif

  if (Use CID?) then (yes)
    :Enable CID for session;
  else (no)

  endif

  :Start DTLS handshake;
  if (Handshake successful?) then (yes)
    repeat
      :Initialize Confirmable CoAP PUT message;
      :Add Message ID and Token to CoAP message;
      :Encrypt and send CoAP message with WolfSSL;
      :Await response;
      if (CoAP ACK received within timeout?) then (yes)
        :Verify CoAP ACK;
      else (no)
        :Assume IP change, reset DTLS context;
        :Start new DTLS Handshake;
      endif
    repeat while (CoAP messages remaining to be sent?) is (yes)
  else (no)
  endif
    :Shutdown DTLS session;
else (no)
  :Log LTE connection failure;
endif

stop
@enduml
